"""check_parity.py

Compare Python solve_value_function output against Julia reference outputs
stored in parity_reference/ (generated by export_julia_reference.jl).

Parameters match export_julia_reference.jl exactly:
    epsilon=16.0, gamma=0.9  ->  eps*(1-gamma)=1.6 > 1
    This is the regime where the Brent fallback fires, so this check
    directly validates both correctness and convergence of the new code.

Run from Code/PythonEstimation/:
    python check_parity.py
"""
import math
import time

import numpy as np

from model_functions import Parameters, solve_value_function

REF = "parity_reference"


def load_ref(name):
    return np.loadtxt(f"{REF}/{name}.csv", delimiter=",")


# ── Julia reference ───────────────────────────────────────────────────────────
sgrid_ref      = load_ref("sgrid").ravel()
omega_ref      = load_ref("omega_grid").ravel()
pi_omega_ref   = load_ref("pi_omega").ravel()
p_omega_ref    = load_ref("p_omega")
v_ref          = load_ref("v").ravel()
n_policy_ref   = load_ref("n_policy")
p_policy_ref   = load_ref("p_policy")
v_by_omega_ref = load_ref("v_by_omega")
converged_ref  = bool(int(load_ref("converged").ravel()[0]))

print("Julia reference outputs:")
print(f"  converged:  {converged_ref}")
print(f"  sgrid:      {sgrid_ref.shape}  [{sgrid_ref[0]:.3f}, {sgrid_ref[-1]:.3f}]")
print(f"  omega_grid: {omega_ref.shape}  [{omega_ref[0]:.4f}, {omega_ref[-1]:.4f}]")
print(f"  p_policy:   {p_policy_ref.shape}  [{p_policy_ref.min():.3f}, {p_policy_ref.max():.3f}]")
print(f"  n_policy:   {n_policy_ref.shape}  [{n_policy_ref.min():.3f}, {n_policy_ref.max():.3f}]")
print()

# ── Python Parameters (must match export_julia_reference.jl) ─────────────────
params = Parameters(
    c=1.0,
    fc=0.0,
    mu_eta=math.log(0.01),   # Julia: μη=log(0.01)
    sigma_eta2=0.05,
    rho_omega=0.1,
    gamma=0.9,
    delta=0.005,
    beta=0.995,
    epsilon=16.0,
    mu_nu=1.0,
    sigma_nu2=0.05,
    ns=200,
    scale=1.0,
    size=100.0,
)

print(f"Parameter regime: eps*(1-gam) = {params.epsilon*(1-params.gamma):.1f}  "
      f"(> 1 -> Brent fallback path)")
print()

# ── Grid alignment ────────────────────────────────────────────────────────────
print("Grid alignment (Python vs Julia):")
print(f"  sgrid max |diff|:      {np.max(np.abs(params.sgrid      - sgrid_ref)):.2e}")
print(f"  omega_grid max |diff|: {np.max(np.abs(params.omega_grid - omega_ref)):.2e}")
print(f"  pi_omega max |diff|:   {np.max(np.abs(params.pi_omega   - pi_omega_ref)):.2e}")
print(f"  p_omega max |diff|:    {np.max(np.abs(params.p_omega    - p_omega_ref)):.2e}")
print()

# ── Solve ─────────────────────────────────────────────────────────────────────
print("Solving (first call — may include JIT recompilation)...")
t0 = time.perf_counter()
sol = solve_value_function(params, tol=1e-3, maxiter=1000, conv="policy")
t_first = time.perf_counter() - t0
print(f"  {t_first:.2f}s   converged={sol['converged']}   iterations={sol['iterations']}")

print("Solving again (warmed JIT)...")
t0 = time.perf_counter()
sol = solve_value_function(params, tol=1e-3, maxiter=1000, conv="policy")
t_warm = time.perf_counter() - t0
print(f"  {t_warm:.2f}s   converged={sol['converged']}   iterations={sol['iterations']}")
print()

if not sol["converged"]:
    print("WARNING: Python solve did not converge. Parity numbers will be unreliable.")
    print()

# ── Parity comparison ─────────────────────────────────────────────────────────
def report(label, py_arr, ref_arr, skip_s0=True):
    """Print max/mean absolute and relative differences, skipping the s=0 row."""
    py  = np.asarray(py_arr, dtype=float)
    ref = np.asarray(ref_arr, dtype=float)
    if skip_s0:
        py  = py[1:] if py.ndim == 1 else py[1:, :]
        ref = ref[1:] if ref.ndim == 1 else ref[1:, :]
    diff = np.abs(py - ref)
    rel  = diff / (np.abs(ref) + 1e-10)
    print(f"  {label:<20}  max_abs={diff.max():.3e}  "
          f"mean_abs={diff.mean():.3e}  max_rel={rel.max():.3e}")

print("Parity vs Julia (s=0 row excluded — trivially 1.0 in both):")
report("p_policy",   sol["p_policy"],   p_policy_ref)
report("n_policy",   sol["n_policy"],   n_policy_ref)
report("v_by_omega", sol["v_by_omega"], v_by_omega_ref)
report("v (marg.)",  sol["v"],          v_ref)
print()

# ── Price policy detail ───────────────────────────────────────────────────────
# Show where the largest p_policy deviations occur.
p_diff = np.abs(sol["p_policy"][1:, :] - p_policy_ref[1:, :])
flat_idx = np.argmax(p_diff)
si, oi = np.unravel_index(flat_idx, p_diff.shape)
print(f"Largest p_policy deviation:")
print(f"  s_index={si+1}  omega_index={oi}  "
      f"s={params.sgrid[si+1]:.3f}  omega={params.omega_grid[oi]:.4f}")
print(f"  Python={sol['p_policy'][si+1, oi]:.6f}  "
      f"Julia={p_policy_ref[si+1, oi]:.6f}  diff={p_diff.max():.3e}")
print()

# ── Timing summary ────────────────────────────────────────────────────────────
print("Timing:")
print(f"  First call (incl. any JIT compilation): {t_first:.2f}s")
print(f"  Warmed solve:                           {t_warm:.2f}s")
print(f"  VFI iterations (warmed):                {sol['iterations']}")
if sol['iterations'] > 0:
    print(f"  Approx time per iteration:              "
          f"{1000*t_warm/sol['iterations']:.1f}ms")
